# Generated by Django 2.0.7 on 2018-07-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='products_type',
            field=models.CharField(choices=[('drinks', 'Bebida'), ('food', 'Comida'), ('candy', 'Doce')], default='food', max_length=10),
        ),
    ]
